# Build front-end static sources
.build_dist:
  image:
    name: quay-hub.pid.prod/platform/nodev16:latest
  stage: build
  tags:
    - local-docker
  except:
    refs:
      - triggers
      - pipelines
  before_script:
    - echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
    - echo 'yarn-offline-mirror-pruning true' >> .yarnrc
    - yarn install --frozen-lockfile --no-progress
  script:
    - pwd
    - ls -l node_modules/ | wc -l
    - ln -fs ${APP_ENV}/env.ts src/env/index.ts
    - yarn build 2>&1 | tee build_result.tmp
    - |
      if [[ `grep -w -E "failed" build_result.tmp` ]]
      then
        echo "Build failed"
        exit 1
      fi
    - ls -al
    - du -sh dist/
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
  artifacts:
    name: '$CI_COMMIT_SHORT_SHA'
    paths:
      - dist/
    expire_in: 5 mins

build:dist:dev:
  extends: .build_dist
  only:
    - dev
  variables:
    APP_ENV: dev
    GIT_SUBMODULE_STRATEGY: recursive

build:dist:qa:
  extends: .build_dist
  only:
    - qa
  variables:
    APP_ENV: qa
    GIT_SUBMODULE_STRATEGY: recursive

build:dist:prod:
  extends: .build_dist
  only:
    - master
  variables:
    APP_ENV: prod
    GIT_SUBMODULE_STRATEGY: recursive