# Deploy front-end image to service
# 發布 gcp 模板
.deploy_template:
  image:
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:353.0.0
    entrypoint:
      ['/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0']
  stage: deploy
  tags:
    - gce-gitlab-runner-ssd
  variables:
    GIT_STRATEGY: none
  before_script:
    - echo ${SERVICE_ACCOUNT_KEY} > $HOME/.config/key.json
    - gcloud auth activate-service-account ${SERVICE_ACCOUNT} --key-file=$HOME/.config/key.json
    - gcloud config set project {PROJECT}
    - echo ${CLUSTER}
    - gcloud container clusters get-credentials ${CLUSTER} --region asia-east1-b
    # - gcloud auth configure-docker asia-east1-docker.pkg.dev
    - kubectl config set-context --current --namespace=hex
  script:
    - POD=deployment/bin-pod-nginx-admin-v3
    - >-
      CONTAINER_NAME=($(kubectl describe ${POD} | grep -B1 Image | awk '{print $1}' | grep -v "Image\|--" | tr  ':\n'  ' '))
      CONTAINER_IMAGE=($(kubectl describe ${POD} | grep Image | awk '{print $2}'))
      UPDATE_IMAGE="kubectl set image ${POD}"

      for ((i=0; i < ${#CONTAINER_NAME[@]}; i++))
      do
          UPDATE_IMAGE="${UPDATE_IMAGE} ${CONTAINER_NAME[$i]}=${CONTAINER_IMAGE[$i]}"
      done

      echo "export ROLLBACK_COMMAND=\"${UPDATE_IMAGE}\"" >> ./rollback_command
    - cat ./rollback_command
    - IMAGE=asia-east1-docker.pkg.dev/{PROJECT_ID}/web/bin-vector/${CI_PROJECT_NAME}-nginx:${APP_ENV}-${CI_COMMIT_SHORT_SHA}
    - kubectl set image ${POD} nginx=${IMAGE}
  artifacts:
    paths:
      - ./rollback_command

# 自動發布到開發站
deploy:dev:
  extends: .deploy_template
  only:
    refs:
      - dev
  variables:
    PROJECT: platform-dev
    PROJECT_ID: gcp-20220425-010
    CLUSTER: platform-dev
    APP_ENV: DEV

# 發布到測試站
deploy:qa:
  extends: .deploy_template
  rules:
    - if: '$CI_COMMIT_TAG =~ /^QA_/'
  variables:
    PROJECT: platform-test
    PROJECT_ID: gcp-20220425-011
    CLUSTER: platform-test
    APP_ENV: QA

# 發布到正式站
deploy:prod:
  extends: .deploy_template
  rules:
    - if: '$CI_COMMIT_TAG =~ /^Prod_/'
  variables:
    PROJECT: platform-prod
    PROJECT_ID: gcp-20220425-012
    CLUSTER: platform-prod
    APP_ENV: Prod
