# Test front-end before merge to main branch
# 編譯前腳本 (link等執行腳本)
.before_test_build:
  script:
    - ln -fs dev/env.ts src/env/index.ts
    - ln -fs qa/game/index.js src/languages/gamedict/game.js
    - ln -fs qa/report/index.js src/languages/gamedict/report.js
    - ln -fs qa/relate/index.js src/languages/gamedict/relate.js
    - ln -fs qa/playtype/index.js src/languages/gamedict/playtype.js
    - ln -fs qa/round_result/index.js src/languages/gamedict/round_result.js

# 測試前置動作
.test:
  image:
    name: gcr.io/rd6-project/platform/front/node:v16
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - gce-gitlab-runner-ssd
  only:
    - merge_requests
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
      - node_modules/
  before_script:
    # check node_modules exist
    - echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
    - echo 'yarn-offline-mirror-pruning true' >> .yarnrc
    - yarn install --frozen-lockfile --no-progress
    - !reference [.before_test_build, script]
    - |
      if [[ `test -d node_modules && echo "" || echo "error"` ]]
      then
          echo "node_modules not found"
          exit 1
      fi
    - pwd

# 測試 Lint 工具
test:lint:
  extends: .test
  script:
    - ls -al
    - yarn lint 2>&1 | tee lint_result.tmp
    - |
      if [[ `grep -w -E "ERROR|Errors|error" lint_result.tmp` ]]
      then
        echo "Lint tool detected ERROR !"
        exit 1
      fi
    - |
      if [[ `grep -w -E "WARNING|warning" lint_result.tmp` ]]
      then
        echo "Lint tool detected WARNING !"
        exit 1
      fi
  artifacts:
    paths:
      - lint_result.tmp

# 測試編譯
test:build:
  extends: .test
  script:
    - yarn build 2>&1 | tee build_result.tmp
    - |
      if [[ `grep -w -E "failed" build_result.tmp` ]]
      then
        echo "Build failed"
        exit 1
      fi
    - ls -al
    - du -sh dist/
  artifacts:
    paths:
      - build_result.tmp

# 測試 console.log 語法是否無刪除
test:console:
  stage: test
  tags:
    - gce-gitlab-runner-ssd
  only:
    - merge_requests
  script:
    - pwd
    - ls -Al
    - if grep -rn --include \*.vue --include \*.js console.log src; then echo "src contains console.log"; exit 1; fi;

# sync test
.sync-test:
  image:
    name: gcr.io/rd6-project/platform/front/node:v16
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - gce-gitlab-runner-ssd
  only:
    - triggers
    - pipelines
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
      - node_modules/
  before_script:
    # check node_modules exist
    - echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
    - echo 'yarn-offline-mirror-pruning true' >> .yarnrc
    - yarn install --frozen-lockfile --no-progress
    - !reference [.before_test_build, script]
    - |
      if [[ `test -d node_modules && echo "" || echo "error"` ]]
      then
          echo "node_modules not found"
          exit 1
      fi
    - pwd

# 合併前測試編譯
test:sync-build:
  extends: .sync-test
  script:
    - yarn build 2>&1 | tee build_result.tmp
    - |
      if [[ `grep -w -E "failed" build_result.tmp` ]]
      then
        echo "Build failed"
        exit 1
      fi
    - ls -al
    - du -sh dist/
